apiVersion: v1
kind: Secret
metadata:
  name: url-shortener-secrets
type: Opaque
data:
  # These are placeholder base64 encoded values
  # Replace with actual values before deployment
  database-host: ZGItaG9zdA==  # db-host
  database-port: NTQzMg==      # 5432
  database-username: dXNlcm5hbWU=  # username
  database-password: cGFzc3dvcmQ=  # password
  database-name: dXJsc2hvcnRlbmVy  # urlshortener
  jwt-secret: c2VjcmV0LWtleS1mb3Itand0  # secret-key-for-jwt
